name       : libkdepim
version    : 21.12.1
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/libkdepim-21.12.1.tar.xz : d6ad6c6efe130390f854969c420a91d5a87c6fe89fee14e8ca8b32cca358bb3c
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kitemviews-devel
    - kjobwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
