name       : libkdepim
version    : 23.04.2
release    : 69
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/libkdepim-23.04.2.tar.xz : 11c56b7d8e0f24ba28ff84a69d7eb68739e55c6b2f6b68f17b7221422ddb410c
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kitemviews-devel
    - kjobwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
