name       : libkdepim
version    : 21.04.3
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/libkdepim-21.04.3.tar.xz : 5fd0fe9a01c764d3c191557c2dd4d71569cf912867c5bf36fcc79e94c11ff9b6
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kitemviews-devel
    - kjobwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
