name       : libkdepim
version    : 18.08.1
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/libkdepim-18.08.1.tar.xz : c93f27a11b2a51ba186851f02043002140df013a37d6b0934639b41272f10767
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdelibs4support-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kldap-devel
    - kmime-devel
    - kwallet-devel
    - libboost-devel
    - libical-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
