name       : libkdepim
version    : 19.04.2
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.2/src/libkdepim-19.04.2.tar.xz : 384a61e05f75d205ac42a3437f8ee874776f48848505b67b2a1af940c0214659
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdelibs4support-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kldap-devel
    - kmime-devel
    - kwallet-devel
    - libboost-devel
    - libical-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
