name       : libkdepim
version    : 17.12.1
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/libkdepim-17.12.1.tar.xz : 7ea70d509240a79e7da404f78fe3715c59d11f7f84934ab0683f4d4d8365cfc0
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Libraries for KDE PIM applications.
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdelibs4support-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kldap-devel
    - kmime-devel
    - kwallet-devel
    - libboost-devel
    - libical-devel
    - openldap-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
