name       : libkdepim
version    : 21.04.1
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/libkdepim-21.04.1.tar.xz : 3b6fbcfe4ce01fa9e5f2ec07c63ca1057aaaafbbdbe3915fc4cc2ae0d358448d
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kitemviews-devel
    - kjobwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
