name       : libkdepim
version    : 21.08.3
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/libkdepim-21.08.3.tar.xz : 6084b80880c4e3ba280fc23f41a9ef5dcb3d6be799519433137222d4be74e69c
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kitemviews-devel
    - kjobwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
