name       : libkdepim
version    : 19.08.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.0/src/libkdepim-19.08.0.tar.xz : 4ff394bda799ebe700d12d60ab8171c64e054c6acb105870cd955b5ddce42eab
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdelibs4support-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kldap-devel
    - kmime-devel
    - kwallet-devel
    - libboost-devel
    - libical-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
