name       : libkdepim
version    : 20.08.1
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/libkdepim-20.08.1.tar.xz : a2fb769239283e7f536d4779089ad8664d1498cf7520f057589bf0285630fb4b
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - kcmutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kio-devel
    - kjobwidgets-devel
    - kldap-devel
    - kmime-devel
    - kwindowsystem-devel
    - libboost-devel
    - libical-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
