name       : libkdepim
version    : 19.08.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/libkdepim-19.08.1.tar.xz : 46966eaae2bc71a5bab0c22bcfff858e299d7f1cec2203c1d12cebbc084ee9ce
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kldap-devel
    - kmime-devel
    - kwallet-devel
    - libboost-devel
    - libical-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
