name       : libkdepim
version    : 20.04.1
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/libkdepim-20.04.1.tar.xz : 0a36c8b799f102cc3ca4a880297ba2a14ba371f7d7f53cea9baf2b1a4c995a2d
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kldap-devel
    - kmime-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libical-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
