name       : libkdepim
version    : 23.04.1
release    : 68
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/libkdepim-23.04.1.tar.xz : d0644a0a22c549a1e92cb3ba3648feffc3fceb8de0a8935d2d9d6b6917daae28
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kitemviews-devel
    - kjobwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
