name       : libkdepim
version    : 20.08.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.0/src/libkdepim-20.08.0.tar.xz : 4f5f0688529d13c10c1c3509f64874a069a5d6cae84f81b258b1d081e86771e0
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - kcmutils-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kio-devel
    - kjobwidgets-devel
    - kldap-devel
    - kmime-devel
    - kwindowsystem-devel
    - libboost-devel
    - libical-devel
    - openldap-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
