name       : libkdepim
version    : 21.04.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/libkdepim-21.04.0.tar.xz : 8bb23222eafc0bb3c04a1be4003e27cf7bb00aea9a90b377b3fc5ac970a225aa
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kitemviews-devel
    - kjobwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
