name       : libkdepim
version    : 21.12.0
release    : 58
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/libkdepim-21.12.0.tar.xz : d1330781d2689481f408d1b1c0f3cf1d4adfc231b4a3fe1d5d6d6662cf3ca6cd
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kitemviews-devel
    - kjobwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
