name       : libkdepim
version    : 21.08.1
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/libkdepim-21.08.1.tar.xz : d0859436f3542e8097a61e7b63bbf8f81197b464c8ce6670822dcae0fe49eb83
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Libraries for KDE PIM applications
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - kcompletion-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kitemviews-devel
    - kjobwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
