name       : libkdepim
version    : 17.12.2
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/libkdepim-17.12.2.tar.xz : ef290dd6284a32256e6b9378207eac74b77c761a23d7f142cd2535a322123d19
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Libraries for KDE PIM applications.
description: |
    Libraries for KDE PIM applications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - akonadi-search-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcmutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcontacts-devel
    - kdelibs4support-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kldap-devel
    - kmime-devel
    - kwallet-devel
    - libboost-devel
    - libical-devel
    - openldap-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
